Change password feature completed
beep101/auctionAppBackend pull request #6
Opened 2021-03-07 21:51 UTC by beep101

Reset forgotten password feature
External email service used

2021-03-08 13:44 UTC, farukatlant requested changes
Few improvements

2021-03-08 13:44 UTC, farukatlant commented on ui/src/components/newPassword.js
> +                    <input className="inputFieldWide" id="passwd" name="password" type="password"  onChange={this.onChange} value={this.state.password}/><br/>
final break not necessary

2021-03-08 13:44 UTC, farukatlant commented on ui/src/components/newPassword.js
> +                {this.state.msg==""?null:<p className="warningMessage">{this.state.msg}</p>}
we have interesting improvement here with `this.state.msg && <p ...`

2021-03-08 13:44 UTC, farukatlant commented on ui/src/apiConsumer/accountConsumer.js
> +    post("newPassword",{fpToken:token,password:password}).then(
rename fp to forgotPassword everywhere, easier to understand

2021-03-08 13:44 UTC, farukatlant commented on ui/src/apiConsumer/accountConsumer.js
> +    post("forgotPassword",{email:email}).then(
we can just pass { email } here

2021-03-08 13:44 UTC, farukatlant commented on src/main/java/com/example/demo/services/AccountService.java
> +	private String link="http://localhost:8080/newPassword?token=";
don't use localhost:8000, will be very dificult when deployed to heroku to manage this

2021-03-08 13:44 UTC, farukatlant commented on src/main/java/com/example/demo/services/AccountService.java
> +		List<User> users=usersRepo.findByEmail(forgotPassword.getEmail());
make findByEmail return single user

2021-03-08 13:44 UTC, farukatlant commented on src/main/java/com/example/demo/services/AccountService.java
> +		List<User> users=usersRepo.findByFpTokenAndFpTokenEndtimeAfter(newPassword.getFpToken(),new Timestamp(System.currentTimeMillis()));
similar, change to Optional<User> for return value

2021-03-08 13:44 UTC, farukatlant commented on src/main/java/com/example/demo/entities/User.java
> +	@Column(name="fptokenendtime")
rename to forgot_password_token_end_time

2021-03-08 13:44 UTC, farukatlant commented on src/main/java/com/example/demo/services/AccountService.java
> +		user.setFpTokenEndtime(new Timestamp(System.currentTimeMillis()+24*60*60*1000));
extract 24*60*60*1000 to constant with descriptive

2021-03-08 13:44 UTC, farukatlant commented on src/test/java/com/example/demo/services/AccountServiceTests.java
> +import ch.qos.logback.classic.pattern.ClassOfCallerConverter;
not used

2021-03-08 13:44 UTC, farukatlant commented on ui/src/components/newPassword.js
> +        let token=queryString.parse(this.props.location.search)['token'];
can be const

2021-03-08 14:22 UTC, beep101 commented on ui/src/components/newPassword.js
> +                {this.state.msg==""?null:<p className="warningMessage">{this.state.msg}</p>}
???

2021-03-08 14:29 UTC, farukatlant commented on ui/src/components/newPassword.js
> +                {this.state.msg==""?null:<p className="warningMessage">{this.state.msg}</p>}
this is not professional way to reply to comment

2021-03-09 08:06 UTC, farukatlant approved these changes

2021-03-09 08:06 UTC, merged